/* embed-models.mjs — bake objects/*.stl into objects/models.js as base64.
 *
 *   node tools/embed-models.mjs
 *
 * The page is meant to run straight off the filesystem, and file:// forbids
 * fetch, so the models travel inside a script instead. Run this after adding or
 * changing an STL; tools/bundle.mjs runs it for you.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = resolve(root, 'objects');

const files = readdirSync(dir).filter(f => f.toLowerCase().endsWith('.stl')).sort();

const entries = files.map(f => {
  const b64 = readFileSync(resolve(dir, f)).toString('base64');
  return '  ' + JSON.stringify(basename(f)) + ': "' + b64 + '"';
});

const out =
  '/* Generated by tools/embed-models.mjs — do not edit.\n' +
  ' * STL models as base64, so the page works from the filesystem where fetch cannot. */\n' +
  '(function (R) {\n' +
  '  R.modelData = {\n' + entries.join(',\n') + '\n  };\n' +
  '})(window.Rel = window.Rel || {});\n';

writeFileSync(resolve(dir, 'models.js'), out);

for (const f of files) {
  const bytes = readFileSync(resolve(dir, f)).length;
  console.log('  ' + f.padEnd(16) + (bytes / 1024).toFixed(0).padStart(5) + ' kB');
}
console.log('objects/models.js  ' + (Buffer.byteLength(out) / 1024).toFixed(0) + ' kB');
